const menuData = [
  {
    id: 1,
    img: '/assets/menu/paela.png',
    title: 'Paela',
    para: 'A flavourful Spanish rice dish cooked with a mix of seafood, chicken and vegetables, seasoned with aromatic spices.',
    ing: 'Rice / Saffron / Onion / Garlic / Bell peppers / Tomatoes / Chorizo / Chicken / Seafood / Lemon.',
    price: '8.50',
  },
  {
    id: 2,
    img: '/assets/menu/newplate .png',
    title: 'Capricciosa',
    para: 'A mix of flavors featuring tangy tomato sauce, savory mozzarella cheese, fresh mushrooms, salty ham, and black olives. ',
    ing: 'Onions / Fresh flat-leaf parsley / Mashed potatoes / Pepper / Eggs / Tartare sauce.',
    price: '8.50',
  },
  {
    id: '3',
    img: '/assets/menu/newsalad.png',
    title: 'Caesar Salad',
    para: 'Crisp romaine lettuce, savory Caesar dressing, and crunchy croutons come together in our classic Caesar salad. ',
    ing: 'Romaine lettuce / Caesar dressing / Croutons / Parmesan cheese / Black pepper / Grilled chicken.',
    price: '8.00',
  },
  {
    id: '4',
    img: '/assets/menu/newpizza (1).png',
    title: 'Pizza ',
    para: 'Savory pepperoni slices, gooey mozzarella cheese, and zesty tomato sauce, all baked to perfection on our home made crust.',
    ing: 'Pizza dough / Tomato sauce / Mozzarella cheese / Pepperoni slices / Italian seasoning.',
    price: '8.00',
  },
  {
    id: '5',
    img: '/assets/menu/newfettucine (1).png',
    title: 'Fettucine',
    para: 'Creamy alfredo sauce, topped with savory grilled chicken, shavings of parmesan cheese, and a sprinkling of fresh parsley.',
    ing: 'Fettuccine pasta / Alfredo sauce / Parmesan cheese / Garlic / Butter / Heavy cream / Salt / Black pepper.',
    price: '8.00',
  },
  {
    id: '6',
    img: '/assets/menu/newbuc.png',
    title: 'Bucantini',
    para: 'Bucatini pasta topped with savory authentic pancetta, freshly grated pecorino cheese, and a sprinkle of black pepper.',
    ing: 'Bucatini / Fresh vegetables / Tomatoes / Olives / Feta / Italian dressing.',
    price: '7.50',
  },
  {
    id: '7',
    img: '/assets/menu/hummus.png',
    title: 'Hummus ',
    para: 'Creamy hummus served with warm pita bread, fresh veggies, and a drizzle of olive oil. Perfect for  enjoying a flavorful starter.',
    ing: 'Chickpeas / Garlic / Cilantro / Cumin / Coriander / Onion / Flour.',
    price: '4.99',
  },
  {
    id: '8',
    img: '/assets/menu/spanakopita.png',
    title: 'Spanakopita',
    para: 'A traditional Greek dish made with flaky phyllo dough filled with a savory mixture of spinach, feta cheese, onions, and herbs.',
    ing: 'Spinach / Feta cheese / Phyllo dough / Onions / Eggs / Dill.',
    price: '5.99',
  },
  {
    id: '9',
    img: '/assets/menu/newfalafel - removebg-preview (1).png',
    title: 'Falafel',
    para: 'Crispy and flavorful vegetarian patties made with a blend of chickpeas, herbs, and spices. Served with tahini sauce.',
    ing: 'Chickpeas / Garlic / Cilantro / Cumin / Coriander / Onion / Flour.',
    price: '4.99',
  },
  {
    id: '10',
    img: '/assets/menu/kunafa (1) (1).png',
    title: 'Kunafa',
    para: 'A Middle Eastern dessert made with shredded phyllo dough, filled with sweet cheese or nuts, and drizzled with a fragrant syrup.',
    ing: 'Kataifi dough / Butter / Ricotta cheese / Sugar syrup / Pistachios.',
    price: '5.00',
  },
  {
    id: '11',
    img: '/assets/menu/tiramisu.png',
    title: 'Tiramisu',
    para: 'Our classic tiramisu features layers of espresso-soaked creamy mascarpone cheese, and a dusting of cocoa powder perfect for dessert.',
    ing: 'Ladyfingers / Mascarpone cheese / Eggs / Sugar / Coffee / Cocoa powder.',
    price: '6.00',
  },
  {
    id: '12',
    img: '/assets/menu/newice-cream.png',
    title: 'Gelato',
    para: 'Indulge in our creamy and flavorful gelato, made with the finest ingredients and served in a variety of delicious flavors, Perfect for  dessert',
    ing: 'Milk / Sugar / Cream / Egg yolks / Vanilla / Flavorings.',
    price: '3.50',
  },
]

export { menuData }
